version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "getAsterisk"
    assignees:
      - "getAsterisk"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
    ignore:
      # Ignore major version updates for core dependencies
      - dependency-name: "tauri"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tokio"
        update-types: ["version-update:semver-major"]
      - dependency-name: "serde"
        update-types: ["version-update:semver-major"]
    groups:
      tauri-ecosystem:
        patterns:
          - "tauri*"
          - "@tauri-apps/*"
      testing:
        patterns:
          - "tempfile"
          - "serial_test"
          - "test-case"
          - "once_cell"
          - "proptest"
          - "pretty_assertions"

  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "getAsterisk"
    assignees:
      - "getAsterisk"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
    ignore:
      # Ignore major version updates for React ecosystem
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
      tauri-frontend:
        patterns:
          - "@tauri-apps/*"
      ui-components:
        patterns:
          - "@radix-ui/*"
          - "lucide-react"
          - "framer-motion"
      build-tools:
        patterns:
          - "vite*"
          - "@vitejs/*"
          - "typescript"
          - "@types/*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "getAsterisk"
    assignees:
      - "getAsterisk"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      actions:
        patterns:
          - "actions/*"
          - "softprops/*"
          - "peter-evans/*"