name: Dependency Updates

on:
  schedule:
    # Run every Monday at 6 AM UTC
    - cron: '0 6 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-rust-dependencies:
    runs-on: ubuntu-22.04
    name: Update Rust Dependencies

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            build-essential \
            libssl-dev \
            libsoup-3.0-dev \
            libjavascriptcoregtk-4.1-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-edit
        run: cargo install cargo-edit

      - name: Update Rust dependencies
        working-directory: src-tauri
        run: |
          # Update all dependencies to latest compatible versions
          cargo update
          
          # Try to upgrade to latest versions (may require manual review)
          cargo upgrade --workspace --dry-run > upgrade-output.txt
          
          # Only upgrade patch versions automatically
          cargo upgrade --workspace --pinned
          
          # Check if Cargo.lock was modified
          if git diff --exit-code Cargo.lock; then
            echo "no_changes=true" >> $GITHUB_ENV
          else
            echo "no_changes=false" >> $GITHUB_ENV
          fi

      - name: Run tests after update
        if: env.no_changes == 'false'
        working-directory: src-tauri
        run: |
          cargo test --all-features
          cargo clippy -- -D warnings

      - name: Create Pull Request
        if: env.no_changes == 'false'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update Rust dependencies'
          title: 'chore: Update Rust dependencies'
          body: |
            ## 🤖 Automated Dependency Update
            
            This PR updates Rust dependencies to their latest compatible versions.
            
            ### Changes
            - Updated Cargo.lock with latest dependency versions
            - All tests pass with updated dependencies
            
            ### Review Notes
            - This is an automated update that only includes patch-level changes
            - Major version updates are excluded and require manual review
            - All tests and linting checks have passed
            
            **Please review carefully before merging.**
          branch: chore/update-rust-deps
          delete-branch: true

  update-frontend-dependencies:
    runs-on: ubuntu-22.04
    name: Update Frontend Dependencies

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Update frontend dependencies
        run: |
          # Update all dependencies
          bun update
          
          # Check if package.json or bun.lock was modified
          if git diff --exit-code package.json bun.lock; then
            echo "no_changes=true" >> $GITHUB_ENV
          else
            echo "no_changes=false" >> $GITHUB_ENV
          fi

      - name: Run tests after update
        if: env.no_changes == 'false'
        run: |
          bun install
          bunx tsc --noEmit

      - name: Create Pull Request
        if: env.no_changes == 'false'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update frontend dependencies'
          title: 'chore: Update frontend dependencies'
          body: |
            ## 🤖 Automated Frontend Dependency Update
            
            This PR updates frontend dependencies to their latest versions.
            
            ### Changes
            - Updated package.json and bun.lock with latest dependency versions
            - TypeScript compilation passes with updated dependencies
            
            ### Review Notes
            - This is an automated update
            - Type checking has passed with the updated dependencies
            - Manual testing recommended before merging
            
            **Please review carefully before merging.**
          branch: chore/update-frontend-deps
          delete-branch: true

  security-audit:
    runs-on: ubuntu-22.04
    name: Security Audit

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run Rust security audit
        working-directory: src-tauri
        run: |
          cargo audit --json > audit-results.json || true
          
          # Check if there are any vulnerabilities
          if [ -s audit-results.json ] && [ "$(jq '.vulnerabilities.found' audit-results.json)" != "false" ]; then
            echo "vulnerabilities_found=true" >> $GITHUB_ENV
            echo "## 🚨 Security Vulnerabilities Found" > security-report.md
            echo "" >> security-report.md
            echo "\`\`\`json" >> security-report.md
            cat audit-results.json >> security-report.md
            echo "\`\`\`" >> security-report.md
          else
            echo "vulnerabilities_found=false" >> $GITHUB_ENV
          fi

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install frontend dependencies
        run: bun install

      - name: Run frontend security audit
        run: |
          # Bun audit (if available)
          bun audit || true
          
          # Alternative: use npm audit if bun audit is not available
          npx audit-ci --moderate || true

      - name: Create security issue
        if: env.vulnerabilities_found == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'security: address dependency vulnerabilities'
          title: '🚨 Security: Address dependency vulnerabilities'
          body: |
            ## 🚨 Security Vulnerabilities Detected
            
            This automated security audit has detected vulnerabilities in project dependencies.
            
            $(cat security-report.md)
            
            ### Action Required
            
            1. Review the vulnerabilities listed above
            2. Update affected dependencies to secure versions
            3. Test the application thoroughly after updates
            4. Merge this PR only after addressing all security issues
            
            ### Resources
            
            - [Rust Security Database](https://rustsec.org/)
            - [Advisory Database](https://github.com/rustsec/advisory-db)
            
            **⚠️ Do not ignore security vulnerabilities. Address them promptly.**
          branch: security/dependency-vulnerabilities
          delete-branch: true

  dependabot-auto-merge:
    runs-on: ubuntu-22.04
    name: Auto-merge Dependabot PRs
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-merge patch updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}